export CUDA_VISIBLE_DEVICES=1
python train.py \
    --dataname radar\
    -m SimVP \
    --model_type gsta \
    --lr 1e-3  \
    --ex_name radar_simvp_gsta \
    --data_root /home/liufarong/mnt/myvptr/data \
    --batch_size 1 \
    --use_gpu 1 \
    --val_batch_size 1 \
    --pre_seq_length 10 \
    --aft_seq_length 10 \
    --total_length 20 \
    --res_dir   /home/lfr/mnt/Radar_Data/simvp/SimVP_gSTA/6_6 \
    --config_file ./configs/radar/SimVP_gSTA.py \
    --epoch 2 \
    --log_step 1\
    --save_step 1 \
    --train_data_paths small_2000_10.npz \
    --valid_data_paths small_2000_10.npz \
    --test_data_paths small_2000_10.npz \
    --is_train 1 \